<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<!--	Simplified Chinese messages for SSHOUT Qt Client
	Copyright 2015-2020 Rivoreo

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or (at
	your option) any later version.

	This program is distributed in the hope that it will be useful, but
	WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
	General Public License for more details.

	Additional permission under GNU GPL version 3 section 7

	Rivoreo grants you additional permission to distribute the binary
	form of this translated messages file that generated by Qt Linguist,
	either modified or not, without	providing the original XML form, as
	long as the binary format file you distributing is compatible with Qt
	Linguist.
-->
<TS version="2.0" language="zh_CN" sourcelanguage="en_US">
<context>
    <name>ConnectionWindow</name>
    <message>
        <source>Connect to Server</source>
        <translation>连接到服务器</translation>
    </message>
    <message>
        <source>Server</source>
        <translation>服务器</translation>
    </message>
    <message>
        <source>Port</source>
        <translation>端口</translation>
    </message>
    <message>
        <source>Identify</source>
        <translation>私钥文件</translation>
    </message>
    <message>
        <source>&amp;Auto connect</source>
        <translation>自动连接 (&amp;A)</translation>
    </message>
    <message>
        <source>&amp;Settings</source>
        <translation>设置 (&amp;S)</translation>
    </message>
    <message>
        <source>Choose the identity</source>
        <translation>选择私钥文件</translation>
    </message>
    <message>
        <source>Check Server Information</source>
        <translation>检查服务器信息</translation>
    </message>
    <message>
        <source>Host name cannot be empty</source>
        <translation>主机名不能为空</translation>
    </message>
    <message>
        <source>Invalid port number</source>
        <translation>无效的端口号</translation>
    </message>
    <message>
        <source>Identify file path cannot be empty</source>
        <translation>私钥文件路径不能为空</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <source>Broadcast Message:</source>
        <translation>广播消息：</translation>
    </message>
    <message>
        <source>&amp;Server</source>
        <translation>服务器(&amp;S)</translation>
    </message>
    <message>
        <source>&amp;Edit</source>
        <translation>编辑(&amp;E)</translation>
    </message>
    <message>
        <source>&amp;View</source>
        <translation>查看(&amp;V)</translation>
    </message>
    <message>
        <source>&amp;Help</source>
        <translation>帮助(&amp;H)</translation>
    </message>
    <message>
        <source>On-line Users</source>
        <translation>当前在线用户</translation>
    </message>
    <message>
        <source>Private messages will be sent to selected user if checked</source>
        <translation>选中后将会发送私信给选定的用户，而不是广播消息</translation>
    </message>
    <message>
        <source>&amp;PM to selected user</source>
        <translation>私信给选定用户(&amp;P)</translation>
    </message>
    <message>
        <source>Tool Bar</source>
        <translation>工具栏</translation>
    </message>
    <message>
        <source>Press &amp;Enter to send message</source>
        <translation>按 &amp;Enter 键发送消息</translation>
    </message>
    <message>
        <source>&amp;Settings ...</source>
        <translation>设置 (&amp;S) ...</translation>
    </message>
    <message>
        <source>&amp;Change server</source>
        <translation>更换服务器 (&amp;C)</translation>
    </message>
    <message>
        <source>Logout and choose another server</source>
        <translation>登出并重新选择要连接的服务器</translation>
    </message>
    <message>
        <source>&amp;Logout</source>
        <translation>登出 (&amp;L)</translation>
    </message>
    <message>
        <source>Logout and exit</source>
        <translation>登出并退出程序</translation>
    </message>
    <message>
        <source>Send</source>
        <translation>发送</translation>
    </message>
    <message>
        <source>Send your message</source>
        <translation>发送您的消息</translation>
    </message>
    <message>
        <source>Show On-line Users</source>
        <translation>显示在线用户</translation>
    </message>
    <message>
        <source>Send message in HTML format</source>
        <translation>以 HTML 格式发送消息</translation>
    </message>
    <message>
        <source>Send Image...</source>
        <translation>发送图片 ...</translation>
    </message>
    <message>
        <source>&amp;Project page...</source>
        <translation>前往工程页面 (&amp;P) ...</translation>
    </message>
    <message>
        <source>Finding new versions, reporting bugs and gettings the source</source>
        <translation>寻找新版本，报告程序问题，以及获取源码</translation>
    </message>
    <message>
        <source>&amp;About...</source>
        <translation>关于 (&amp;A) ...</translation>
    </message>
    <message>
        <source>Send Image from Clipboard</source>
        <translation>从剪贴板粘贴图片并发送</translation>
    </message>
    <message>
        <source>&amp;Paste</source>
        <translation>粘贴 (&amp;P)</translation>
    </message>
    <message>
        <source>Ctrl+V</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>About &amp;Qt...</source>
        <translation>关于 &amp;Qt ...</translation>
    </message>
    <message>
        <source>Failed to create image cache directory &apos;%1&apos;</source>
        <translation>无法创建图片缓存目录“%1”</translation>
    </message>
    <message>
        <source>Failed to open message log database; messages won&apos;t be logged</source>
        <translation>无法打开消息日志数据库，过往消息将不会被记录</translation>
    </message>
    <message>
        <source>Press %1 to send</source>
        <translation>按下 %1 以发送</translation>
    </message>
    <message>
        <source>Enter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Ctrl-Enter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Cannot connect</source>
        <translation>无法连接</translation>
    </message>
    <message>
        <source>[Failed to load image]</source>
        <translation>[无法载入图片]</translation>
    </message>
    <message>
        <source>Image file &apos;%1&apos; is already exist, skipping write</source>
        <translation>图片文件“%1”已存在，已跳过保存该文件</translation>
    </message>
    <message>
        <source>[Failed to save image to disk, %1]</source>
        <translation>[保存图片到磁盘时失败：%1]</translation>
    </message>
    <message>
        <source>[File %1 short write]</source>
        <translation>[保存文件“%1”时中断]</translation>
    </message>
    <message>
        <source>&lt;font color=&quot;%1&quot;&gt;%2&lt;/font&gt; to &lt;font color=&quot;%3&quot;&gt;%4&lt;/font&gt;  </source>
        <translation>&lt;font color=&quot;%1&quot;&gt;%2&lt;/font&gt; 私信给 &lt;font color=&quot;%3&quot;&gt;%4&lt;/font&gt;  </translation>
    </message>
    <message>
        <source>Cannot send message, server is not connected</source>
        <translation>无法在未连接的服务器时发送消息</translation>
    </message>
    <message>
        <source>Sending message</source>
        <translation>正在发送消息</translation>
    </message>
    <message>
        <source>Preview</source>
        <translation>预览</translation>
    </message>
    <message>
        <source>Cannot export the image as JPEG</source>
        <translation>无法将该图片导出为 JPEG 格式</translation>
    </message>
    <message>
        <source>%1 has %2
</source>
        <translation>%1 已%2
</translation>
    </message>
    <message>
        <source>joined</source>
        <translation>加入</translation>
    </message>
    <message>
        <source>left</source>
        <translation>离开</translation>
    </message>
    <message>
        <source>Error from server: %1</source>
        <translation>来自服务端的错误：%1</translation>
    </message>
    <message>
        <source>Configuration Error</source>
        <translation>配置错误</translation>
    </message>
    <message>
        <source>Configured to use internal SSH library; but known host list is empty</source>
        <translation>已配置为使用内部 SSH 库，但已知信任主机列表是空的</translation>
    </message>
    <message>
        <source>Configured to use separate known host list; but that list is empty.</source>
        <translation>已配置为使用独立的已知主机列表，但该列表是空的。</translation>
    </message>
    <message>
        <source>Connecting</source>
        <translation>正在连接</translation>
    </message>
    <message>
        <source>Authenticating</source>
        <translation>正在认证</translation>
    </message>
    <message>
        <source>Connected</source>
        <translation>已连接</translation>
    </message>
    <message>
        <source>Magic mismatch</source>
        <translation>Magic 不匹配</translation>
    </message>
    <message>
        <source>Version mismatch (%1 != 1)</source>
        <translation>意外的服务端协议版本 %1</translation>
    </message>
    <message>
        <source>You won&apos;t be able to connect to SSH server again, until SSH configuration was corrected.</source>
        <translation>在 SSH 配置问题被修正之前，您将不能再次连接到 SSH 服务器。</translation>
    </message>
    <message>
        <source>Choose an image to upload</source>
        <translation>选择要上载的图片</translation>
    </message>
    <message>
        <source>Cannot load file &apos;%1&apos; as an image</source>
        <translation>无法将文件“%1”作为图片载入</translation>
    </message>
    <message>
        <source>About</source>
        <translation>关于</translation>
    </message>
    <message>
        <source>This program is free software; you are free to change and redistribute it; see the source for copying conditions.</source>
        <translation>此程序为自由软件，您可任意更改并重分发它。要了解分发条款，请查看源代码。</translation>
    </message>
    <message>
        <source>There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.</source>
        <translation>本程序不提供任何担保，即便是针对适销或特定用途的适用性。</translation>
    </message>
    <message>
        <source>&amp;Open Image</source>
        <translation>打开图片 (&amp;O)</translation>
    </message>
    <message>
        <source>Copy &amp;Image</source>
        <translation>复制图片 (&amp;I)</translation>
    </message>
    <message>
        <source>&amp;Copy</source>
        <translation>复制 (&amp;C)</translation>
    </message>
    <message>
        <source>Select All</source>
        <translation>选择全部</translation>
    </message>
    <message>
        <source>Opening %1</source>
        <translation>正在打开 %1</translation>
    </message>
    <message>
        <source>Failed to copy image: invalid image</source>
        <translation>无法复制图片: 无效的图片</translation>
    </message>
    <message>
        <source>ID</source>
        <translation>客户端ID</translation>
    </message>
    <message>
        <source>Host</source>
        <translation>主机</translation>
    </message>
    <message>
        <source>Active Sessions of User %1</source>
        <translation>用户 %1 的活动会话</translation>
    </message>
    <message>
        <source>Dropping to send image</source>
        <translation>丢下以发送该图片</translation>
    </message>
    <message>
        <source>Can&apos;t load &apos;%1&apos; as image: only local files are supported</source>
        <translation>无法将“%1”作为图片载入：只支持本地的文件</translation>
    </message>
    <message>
        <source>No image available from clipboard</source>
        <translation>剪贴板中没有图片可用</translation>
    </message>
    <message>
        <source>Message to &lt;b&gt;%1&lt;/b&gt;:</source>
        <translation>给 &lt;b&gt;%1&lt;/b&gt; 的消息：</translation>
    </message>
    <message>
        <source>An error occurred in SSH client</source>
        <translation>SSH客户端中发生了一个错误</translation>
    </message>
    <message>
        <source>API handshake timed out</source>
        <translation>API握手超时</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>Default</source>
        <translation>默认</translation>
    </message>
</context>
<context>
    <name>SettingsDialog</name>
    <message>
        <source>Settings</source>
        <translation>设置</translation>
    </message>
    <message>
        <source>SSH</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Set separate &amp;known hosts</source>
        <translation>设置独立的已知主机列表(&amp;K)</translation>
    </message>
    <message>
        <source>Use &amp;internal OpenSSH library</source>
        <translation>使用内部 OpenSSH 库</translation>
    </message>
    <message>
        <source>SSH program path</source>
        <translation>SSH 程序路径</translation>
    </message>
    <message>
        <source>...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Addional options for SSH</source>
        <translation>给 SSH 程序的额外选项</translation>
    </message>
    <message>
        <source>Addional Environment:</source>
        <translation>额外的环境变量：</translation>
    </message>
    <message>
        <source>Name</source>
        <translation>名</translation>
    </message>
    <message>
        <source>Value</source>
        <translation>值</translation>
    </message>
    <message>
        <source>+</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>-</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Interface</source>
        <translation>用户界面</translation>
    </message>
    <message>
        <source>Style</source>
        <translation>风格</translation>
    </message>
    <message>
        <source>Show &amp;Tray Icon</source>
        <translation>显示托盘图标(&amp;T)</translation>
    </message>
    <message>
        <source>Notification</source>
        <translation>通知</translation>
    </message>
    <message>
        <source>&amp;Window Alert</source>
        <translation>闪动窗口</translation>
    </message>
    <message>
        <source>Tray &amp;Popup</source>
        <translation>托盘区通知消息(&amp;P)</translation>
    </message>
    <message>
        <source>Play &amp;Sound</source>
        <translation>播放提示音(&amp;S)</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>文本</translation>
    </message>
    <message>
        <source>Default font family</source>
        <translation>默认字体族</translation>
    </message>
    <message>
        <source>Default font size</source>
        <translation>默认字体大小</translation>
    </message>
    <message>
        <source>&amp;Hide to Tray when Minimized</source>
        <translation>最小化时隐藏到托盘区(&amp;H)</translation>
    </message>
    <message>
        <source>Language</source>
        <translation>界面语言</translation>
    </message>
    <message>
        <source>Image</source>
        <translation>图片</translation>
    </message>
    <message>
        <source>Override default JPEG quality</source>
        <translation>自定义 JPEG 质量</translation>
    </message>
    <message>
        <source>Default</source>
        <translation>默认</translation>
    </message>
    <message>
        <source>built-in</source>
        <translation>内建</translation>
    </message>
    <message>
        <source>Choose SSH client program to use</source>
        <translation>选择要使用的 SSH 客户端程序</translation>
    </message>
    <message>
        <source>Warning</source>
        <translation>警告</translation>
    </message>
    <message>
        <source>File %1 is not executable</source>
        <translation>文件 %1 不可执行</translation>
    </message>
</context>
</TS>
